### ISSUE TITLE
don't work

### ISSUE THREAD

**Issue by hamaz562006** [whyynoot/Likee-Video-Downloader#1]
don't work

**Comment by whyynoot** [comment]
Hi! Very glad to see your review. I will see it up very soon, it will be very helpful if you send me your traceback.

**Comment by whyynoot** [comment]
Hi! I checked your issue, everythink works fine.
![image](https://user-images.githubusercontent.com/63478397/120557282-0fc53e80-c3d4-11eb-9a18-2cd8dc0d0a39.png)

**Comment by whyynoot** [comment]
If you still have any problems, just ask.

**Comment by hamaz562006** [comment]
If use example : "https://l.likee.video/v/1SL3Ry" don't work 
how to use? I need

**Comment by whyynoot** [comment]
You have to use a link for a profile. 
All videos from this profile will be downloaded in your explorer.

**Comment by whyynoot** [comment]
For example for this video - u should use https://likee.video/@nika_matin_n/. 
And ALL videos from this profile will be downloaded.
